### ISSUE TITLE
default http vs https behavior

### ISSUE THREAD

**Issue by pearsonca** [ICI3D/ICI3D.github.io#35]
When navigating to "ici3d.org" the default landing is the http rather than https version. This leads to browsers indicating "non secure" when accessing the site.

This is a technical non-issue (we don't transact anything on the site - no data collection, no have-to-be-sure-its-us data sent). However, it is a bit of smudge on the branding.

Should be something fixable in the hosting settings?

**Comment by pearsonca** [comment]
@jrcpulliam please close this with a snippet about changes made with hosting service

**Comment by jrcpulliam** [comment]
This required updating the redirect with the DNS service provider. ici3d.org now redirects to https://www.ici3d.org
